/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SkillRegistry } from "./SkillRegistry";
export * as factories from "./factories";
export { SkillRegistry__factory } from "./factories/SkillRegistry__factory";
