/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SkillRegistry {
  export type SkillRecordStruct = {
    manifestHash: BytesLike;
    storageAddress: string;
    status: BigNumberish;
    ensSubname: string;
    registeredAt: BigNumberish;
    registrant: AddressLike;
  };

  export type SkillRecordStructOutput = [
    manifestHash: string,
    storageAddress: string,
    status: bigint,
    ensSubname: string,
    registeredAt: bigint,
    registrant: string
  ] & {
    manifestHash: string;
    storageAddress: string;
    status: bigint;
    ensSubname: string;
    registeredAt: bigint;
    registrant: string;
  };
}

export interface SkillRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllSkillIds"
      | "getManifestHash"
      | "getSkillRecord"
      | "isRegistered"
      | "owner"
      | "registerSkill"
      | "totalSkills"
      | "transferOwnership"
      | "updateVerificationStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SkillRegistered"
      | "SkillVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllSkillIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getManifestHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSkillRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSkill",
    values: [BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSkills",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVerificationStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllSkillIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManifestHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkillRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSkill",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSkills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationStatus",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillRegisteredEvent {
  export type InputTuple = [
    skillId: BytesLike,
    manifestHash: BytesLike,
    storageAddress: string,
    registrant: AddressLike
  ];
  export type OutputTuple = [
    skillId: string,
    manifestHash: string,
    storageAddress: string,
    registrant: string
  ];
  export interface OutputObject {
    skillId: string;
    manifestHash: string;
    storageAddress: string;
    registrant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkillVerifiedEvent {
  export type InputTuple = [skillId: BytesLike, status: BigNumberish];
  export type OutputTuple = [skillId: string, status: bigint];
  export interface OutputObject {
    skillId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SkillRegistry;
  waitForDeployment(): Promise<this>;

  interface: SkillRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllSkillIds: TypedContractMethod<[], [string[]], "view">;

  getManifestHash: TypedContractMethod<[skillId: BytesLike], [string], "view">;

  getSkillRecord: TypedContractMethod<
    [skillId: BytesLike],
    [SkillRegistry.SkillRecordStructOutput],
    "view"
  >;

  isRegistered: TypedContractMethod<[skillId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerSkill: TypedContractMethod<
    [
      skillId: BytesLike,
      manifestHash: BytesLike,
      storageAddress: string,
      ensSubname: string
    ],
    [void],
    "nonpayable"
  >;

  totalSkills: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateVerificationStatus: TypedContractMethod<
    [skillId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllSkillIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getManifestHash"
  ): TypedContractMethod<[skillId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSkillRecord"
  ): TypedContractMethod<
    [skillId: BytesLike],
    [SkillRegistry.SkillRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[skillId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerSkill"
  ): TypedContractMethod<
    [
      skillId: BytesLike,
      manifestHash: BytesLike,
      storageAddress: string,
      ensSubname: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalSkills"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVerificationStatus"
  ): TypedContractMethod<
    [skillId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SkillRegistered"
  ): TypedContractEvent<
    SkillRegisteredEvent.InputTuple,
    SkillRegisteredEvent.OutputTuple,
    SkillRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SkillVerified"
  ): TypedContractEvent<
    SkillVerifiedEvent.InputTuple,
    SkillVerifiedEvent.OutputTuple,
    SkillVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SkillRegistered(bytes32,bytes32,string,address)": TypedContractEvent<
      SkillRegisteredEvent.InputTuple,
      SkillRegisteredEvent.OutputTuple,
      SkillRegisteredEvent.OutputObject
    >;
    SkillRegistered: TypedContractEvent<
      SkillRegisteredEvent.InputTuple,
      SkillRegisteredEvent.OutputTuple,
      SkillRegisteredEvent.OutputObject
    >;

    "SkillVerified(bytes32,uint8)": TypedContractEvent<
      SkillVerifiedEvent.InputTuple,
      SkillVerifiedEvent.OutputTuple,
      SkillVerifiedEvent.OutputObject
    >;
    SkillVerified: TypedContractEvent<
      SkillVerifiedEvent.InputTuple,
      SkillVerifiedEvent.OutputTuple,
      SkillVerifiedEvent.OutputObject
    >;
  };
}
